### PR TITLE
Initial rate limiter

### PR DESCRIPTION
**Pull request by alexhultman**
WIP PR,

Incredibly simple and static so far

### CODE REVIEW

**Comment by jbenguira** [comment]
Hey Alex

I have accepted your PR + made some changes, please check here:
https://github.com/elestio/cloudgate/commit/fe1ab4f563e064397657d5a0dbc58ed757661f23#diff-b9310ef1cf6d778bc6bcce12fe829543

I have adapted the code to ratelimit per ip, right now it's not even per
appconfig but for the whole cloudgate instance per IP
I believe the global ratelimit should be on the server config (command line
param)

a few remarks:
- It's currently global for the whole cloudgate instance, that's nice for
the global rate limiter per IP
- It would be great to also have a rate limiter per api/ws endpoint

- It's not yet synchronized between threads, so if you have 12 threads, you
can do 12 times the limit
I tried to implement it with shared memory from uWS ... but my code is not
efficient ... I believe it would require more work on the c++ part to get
functions we need for that (setAllIntegers of a category to 0 or something
like that)

[image: image.png]

[image: image.png]

**Comment by alexhultman-2fa** [comment]
Just multiply the timer with number of threads.

**Comment by alexhultman** [comment]
You can also just multiply the counter by thread count. It might deviate a bit but every second things synchronize to 0 so any potential deviation is very short-lived. And since rate limited state is the unlikely scenario anyways I think this is a simple solution. Also it isn't that important that ONLY ALL users are rate-limited or ONLY NO users are.

**Comment by jbenguira** [comment]
I just did it and it seems to work as expected 👍  (multiply the timer with number of threads)

**Pull request merged**
